# Archivo de configuraci贸n de secrets para Streamlit Cloud
# Este archivo puede contener variables de entorno sensibles

# Configuraci贸n de la aplicaci贸n
[app]
name = "CONSORCIO DEJ"
version = "2.0.0"

# Configuraci贸n de desarrollo
[development]
debug = false 